# Generated by Django 4.2.2 on 2023-06-22 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_user_alter_post_author'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='MyUser',
        ),
    ]
